### ISSUE TITLE
Set package directory path

### ISSUE THREAD

**Issue by neapel** [philopon/haddocset#15]
When I'm running it on my machine it's using only the first package path:
```
Global package directory: /usr/local/Cellar/ghc/7.8.3/lib/ghc-7.8.3/package.conf.d
```
Missing my user directory `~/.ghc/x86_64-darwin-7.8.3/package.conf.d`, and of course my local cabal sandbox directory `./.cabal-sandbox/x86_64-osx-ghc-7.8.3-packages.conf.d`

GHC accepts a `-package-db` option, and ghc-pkg has `--package-db` or `-f`, but I can't set this because `--hc-pkg` only allows setting the executable name, no arguments:
```
$ haddocset create --hc-pkg 'ghc-pkg -f ./.cabal-sandbox/x86_64-osx-ghc-7.8.3-packages.conf.d/'
haddocset: ghc-pkg -f .cabal-sandbox/x86_64-osx-ghc-7.8.3-packages.conf.d/: readProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
It would be nice if there was an option to set the package-db path, and perfect if it would automatically read it from the `package-db` key in `./cabal.sandbox.config`.

**Comment by nrolland** [comment]
What is the workflow to use it with stack or 7.8.4 ?

With stack I get 
```
stack --no-system-ghc exec -- haddocset create
[5/5] Create index.
haddock: internal error: /Users/nrolland/.stack/programs/x86_64-osx/ghc-7.8.4/lib/ghc-7.8.4/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not a ghc-pkg db file, wrong file magic number)
```
 
With a 7.8.4 ghc   
```
[5/5] Create index.
Can't parse "/Users/nrolland/.nix-profile/lib/ghc-7.8.4/platformConstants"
```

**Comment by philopon** [comment]
temporary closed
